/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_ghostidentitywasm_free: (a: number, b: number) => void;
export const __wbg_hashchroniclewasm_free: (a: number, b: number) => void;
export const __wbg_pedersencommitmentwasm_free: (a: number, b: number) => void;
export const __wbg_rangeproofresult_free: (a: number, b: number) => void;
export const __wbg_starkaggregateproofwasm_free: (a: number, b: number) => void;
export const aggregate_zk_proofs: (a: number, b: number, c: number) => number;
export const create_balance_proof: (a: number, b: number, c: number, d: number) => any;
export const create_hash_chronicle: (a: number, b: number, c: number, d: number) => number;
export const create_pedersen_commitment: (a: bigint) => number;
export const create_range_proof: (a: bigint, b: number, c: number) => number;
export const derive_ghost_id: (a: number, b: number) => number;
export const ghostidentitywasm_handle: (a: number) => [number, number];
export const ghostidentitywasm_public_key: (a: number) => any;
export const hashchroniclewasm_event_hash: (a: number) => any;
export const init_void_core: () => void;
export const pedersencommitmentwasm_blinding_factor: (a: number) => any;
export const pedersencommitmentwasm_commitment: (a: number) => any;
export const rangeproofresult_commitment: (a: number) => any;
export const rangeproofresult_proof: (a: number) => any;
export const starkaggregateproofwasm_compressed_size: (a: number) => number;
export const starkaggregateproofwasm_merkle_root: (a: number) => any;
export const starkaggregateproofwasm_proof_count: (a: number) => number;
export const verify_range_proof: (a: number, b: number, c: number, d: number) => number;
export const create_bolt11: (a: number, b: number, c: bigint, d: number, e: number, f: bigint, g: number, h: number) => [number, number, number, number];
export const extract_payment_hash: (a: number, b: number) => [number, number, number, number];
export const parse_bolt11: (a: number, b: number) => [number, number, number, number];
export const validate_bolt11: (a: number, b: number) => number;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
